---
  hostname: leaf_1
  loopback0: 192.168.0.8
  loopback1: 192.168.0.18
  l3ip:
  - interface: Ethernet1/1
    ip: 10.0.0.22
    mask: 30
  - interface: Ethernet1/2
    ip: 10.0.128.6
    mask: 30
  loopbacks:
  - interface: loopback0
    ip: 192.168.0.8
    mask: 32
  - interface: loopback1
    ip: 192.168.0.18
    mask: 32
  router_id: 192.168.0.8
  feature:
    - telnet
    - nxapi
    - ospf
    - interface-vlan
