---
  hostname: leaf_1
  loopback0: 192.168.0.11
  loopback1: 192.168.0.111
  l3ip:
  - interface: Ethernet1/1
    ip: 10.0.128.2
    mask: 30
  - interface: Ethernet1/2
    ip: 10.0.128.18
    mask: 30
  loopbacks:
  - interface: loopback0
    ip: 192.168.0.11
    mask: 32
  - interface: loopback1
    ip: 192.168.0.111
    mask: 32
  router_id: 192.168.0.11
  feature:
    - telnet
    - nxapi
    - ospf
    - interface-vlan
