---
  hostname: spine-1
  loopback0: 192.168.0.6
  loopback1: 192.168.0.100
  l3ip:
  - interface: Ethernet1/1
    ip: 10.0.0.21
    mask: 30
  - interface: Ethernet1/2
    ip: 10.0.0.25
    mask: 30
  - interface: Ethernet1/3
    ip: 10.0.0.29
    mask: 30
  - interface: Ethernet1/4
    ip: 10.0.128.1
    mask: 30
  loopbacks:
  - interface: loopback0
    ip: 192.168.0.6
    mask: 32
  - interface: loopback1
    ip: 192.168.0.100
    mask: 32
  router_id: 192.168.0.6
  feature:
    - telnet
    - nxapi
    - ospf
    - interface-vlan
